"""empty message

Revision ID: aaa54f69cf13
Revises: 
Create Date: 2024-10-01 22:53:07.382756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa54f69cf13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('users')
    op.drop_table('messes')
    op.drop_table('usermessenroll')
    op.drop_table('bills')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('menu_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mess_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('menu_date', sa.DATE(), nullable=True),
    sa.Column('breakfast', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lunch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dinner', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('day', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['messes.mess_id'], name='menu_ibfk_1'),
    sa.PrimaryKeyConstraint('menu_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bills',
    sa.Column('bill_no', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mess_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bill_month', sa.DATE(), nullable=True),
    sa.Column('bill_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('bill_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prorated', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['messes.mess_id'], name='bills_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='bills_ibfk_1'),
    sa.PrimaryKeyConstraint('bill_no'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usermessenroll',
    sa.Column('enrollment_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mess_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['messes.mess_id'], name='usermessenroll_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='usermessenroll_ibfk_1'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('messes',
    sa.Column('mess_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mess_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mess_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('monthly_charges', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_day', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('mess_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mobile_no', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mess_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bill_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pay_date', sa.DATE(), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('payment_mode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pay_status', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bill_no'], ['bills.bill_no'], name='payment_ibfk_3'),
    sa.ForeignKeyConstraint(['mess_id'], ['messes.mess_id'], name='payment_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='payment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
